### ISSUE TITLE
🛑 Fast Integration is down

### ISSUE THREAD

**Issue by socheatsok78** [soramitsukhmer/upptime#4]
In [`8c1c6f5`](https://github.com/soramitsukhmer/upptime/commit/8c1c6f5640feb935cbd5151ed2d25d1d021f29db
), Fast Integration (https://web-fast-integration.sorakh.app/) was **down**:
- HTTP code: 502
- Response time: 747 ms

**Comment by soramitsukhmer-admin** [comment]
The site should now be up and running!
